backend:
  name: git-gateway
  branch: main

media_folder: "images/maps"
public_folder: "/images/maps"

collections:
  - name: "maps"
    label: "Map Projects"
    label_singular: "Map Project"
    delete: true
    editor:
      preview: false
    file: "maps.json"
    format: "json"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Location"
        name: "location"
        widget: "string"
      - label: "Date"
        name: "date"
        widget: "datetime"
      - label: "Image"
        name: "image"
        widget: "image"
      - label: "Description"
        name: "description"
        widget: "text"
      - label: "Tags"
        name: "tags"
        widget: "list"
        default: []
      - label: "Map Link"
        name: "maplink"
        widget: "string"
