backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "maps"
    label: "Map Previews"
    folder: "content/maps"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "location", label: "Location", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "tags", label: "Tags", widget: "list" }
      - { name: "image", label: "Preview Image", widget: "image" }
      - { name: "link", label: "Map URL", widget: "string" }
